### 회원가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "1991-10-04",
  "email": "eunjungkim1004@naver.com",
  "name": "기믄정",
  "password": "22445",
  "phone": "010-1111-5555"
}

### 이메일 인증 (고객)
GET http://localhost:8081/signup/customer/verify/?email=eunjungkim1004@naver.com&code=E2r5sKPuHJ

### 로그인 (고객)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "eunjungkim1004@naver.com",
  "password": "22445"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODA1MjA3ODEsImV4cCI6MTY4MDYwNzE4MX0.EA2kvMqGSq3bVCq4gwvPq32IRLis2zQl8TLbzyJtpNQ

### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODA1MjA3ODEsImV4cCI6MTY4MDYwNzE4MX0.EA2kvMqGSq3bVCq4gwvPq32IRLis2zQl8TLbzyJtpNQ

{
  "from": "server",
  "message": "충전",
  "money": 10000
}

#################################

### 회원가입 (셀러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "1991-10-04",
  "email": "eunjungkim1004@naver.com",
  "name": "기믄정",
  "password": "22445",
  "phone": "010-1111-5555"
}

### 이메일 인증 (셀러)
GET http://localhost:8081/signup/seller/verify/?email=eunjungkim1004@naver.com&code=LbnNKRptCc

### 로그인 (셀러)
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "eunjungkim1004@naver.com",
  "password": "22445"
}

### 회원 정보 조회 (셀러)
GET http://localhost:8081/seller/getInfo
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDg5NjYxLCJleHAiOjE2ODA1NzYwNjF9.aBJfkFpNet1B35NSLzz1l8dTaRztAY8A1wjxfa9vju4