### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDg5NjYxLCJleHAiOjE2ODA1NzYwNjF9.aBJfkFpNet1B35NSLzz1l8dTaRztAY8A1wjxfa9vju4

{
  "description": "상품 설명",
  "id": 1,
  "items": [
    {
      "count": 1,
      "name": "아디다스 스탠스미스",
      "price": 10000,
      "productId": 1
    }
  ],
  "name": "아디다스 스탠스미스 한정판"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDg5NjYxLCJleHAiOjE2ODA1NzYwNjF9.aBJfkFpNet1B35NSLzz1l8dTaRztAY8A1wjxfa9vju4

{
  "productId": 1,
  "count": 1,
  "name": "260",
  "price": 60000
}

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDg5NjYxLCJleHAiOjE2ODA1NzYwNjF9.aBJfkFpNet1B35NSLzz1l8dTaRztAY8A1wjxfa9vju4

{
"description": "상품 설명",
"items": [
  {
    "id": 1,
    "count": 2,
    "name": "280",
    "price": 110000
  }
],
"id": 1,
"name": "아디다스 스탠스미스"
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDg5NjYxLCJleHAiOjE2ODA1NzYwNjF9.aBJfkFpNet1B35NSLzz1l8dTaRztAY8A1wjxfa9vju4

{
  "id": 1,
  "count": 2,
  "name": "260",
  "price": 90000
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?id=2
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDg5NjYxLCJleHAiOjE2ODA1NzYwNjF9.aBJfkFpNet1B35NSLzz1l8dTaRztAY8A1wjxfa9vju4

### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=2
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDg5NjYxLCJleHAiOjE2ODA1NzYwNjF9.aBJfkFpNet1B35NSLzz1l8dTaRztAY8A1wjxfa9vju4


### 상품 검색
GET http://localhost:8082/search/product?name=아디다스
Content-Type: application/json

### 상품 상세 검색
GET http://localhost:8082/search/product/detail?productId=1
Content-Type: application/json


### 장바구니 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODA0OTY3NzYsImV4cCI6MTY4MDU4MzE3Nn0.COg3D9aLdBdga6uBxwi4j2JO4NvRPb40-MTGNbwPef8

{
  "description": "상품 설명",
  "id": 1,
  "name": "아디다스 스탠스미스 한정판",
  "productItems": [
    {
      "count": 1,
      "id": 1,
      "name": "아디다스 스탠스미스",
      "price": 10000
    }
  ],
  "sellerId": 1
}