### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNjk0MTg1LCJleHAiOjE2ODA3ODA1ODV9.Qg77giJ6AkHknLm3bp0CI_6Xe7uAcm6UQds3bjQ7vWo

{
  "description": "아디다스 신발입니다.",
  "id": 1,
  "items": [
    {
      "count": 1,
      "name": "아디다스 스탠스미스 한정판",
      "price": 100000,
      "productId": 1
    }
  ],
  "name": "아디다스 스탠스미스"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNjk0MTg1LCJleHAiOjE2ODA3ODA1ODV9.Qg77giJ6AkHknLm3bp0CI_6Xe7uAcm6UQds3bjQ7vWo


{
  "productId": 1,
  "count": 1,
  "name": "260",
  "price": 60000
}

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNjk0MTg1LCJleHAiOjE2ODA3ODA1ODV9.Qg77giJ6AkHknLm3bp0CI_6Xe7uAcm6UQds3bjQ7vWo

{
"description": "아디다스 신발입니다.",
"items": [
  {
    "id": 1,
    "count": 5,
    "name": "아디다스 스탠스미스 한정판",
    "price": 110000
  }
],
"id": 1,
"name": "아디다스 스탠스미스"
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNjk0MTg1LCJleHAiOjE2ODA3ODA1ODV9.Qg77giJ6AkHknLm3bp0CI_6Xe7uAcm6UQds3bjQ7vWo

{
  "id": 1,
  "count": 5,
  "name": "아디다스 스탠스미스 한정판",
  "price": 90000
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?id=2
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNjk0MTg1LCJleHAiOjE2ODA3ODA1ODV9.Qg77giJ6AkHknLm3bp0CI_6Xe7uAcm6UQds3bjQ7vWo

### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=2
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNjk0MTg1LCJleHAiOjE2ODA3ODA1ODV9.Qg77giJ6AkHknLm3bp0CI_6Xe7uAcm6UQds3bjQ7vWo


### 상품 검색
GET http://localhost:8082/search/product?name=아디다스
Content-Type: application/json

### 상품 상세 검색
GET http://localhost:8082/search/product/detail?productId=1
Content-Type: application/json


### 장바구니 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODA2OTQxNTUsImV4cCI6MTY4MDc4MDU1NX0.cc7axJiz2shtrbDV6oy6Rie2wUck0eegtT7UF27gQ-A

{
  "description": "아디다스 신발입니다.",
  "id": 1,
  "name": "아디다스 스탠스미스",
  "productItems": [
    {
      "count": 1,
      "id": 1,
      "name": "아디다스 스탠스미스 한정판",
      "price": 100000
    }
  ],
  "sellerId": 1
}

### 장바구니 보기
GET http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODA2OTQxNTUsImV4cCI6MTY4MDc4MDU1NX0.cc7axJiz2shtrbDV6oy6Rie2wUck0eegtT7UF27gQ-A

### 장바구니 수정
PUT http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODA2OTQxNTUsImV4cCI6MTY4MDc4MDU1NX0.cc7axJiz2shtrbDV6oy6Rie2wUck0eegtT7UF27gQ-A

{
  "customerId": 1,
  "messages": [],
  "products": [
    {
      "description": "아디다스 신발입니다.",
      "id": 1,
      "name": "아디다스 스탠스미스",
      "productItems": [
        {
          "count": 1,
          "id": 1,
          "name": "아디다스 스탠스미스 한정판",
          "price": 100000
        }
      ],
      "sellerId": 1
    }
  ]
}

### 장바구니 주문
POST http://localhost:8082/customer/cart/order
Content-Type: application/json
X-AUTO-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJcHluRS8veDhWSE03NUo5Q0EvS2pXOHNOam9UVDJmK0d3WjZySzdYWDRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODA2OTQxNTUsImV4cCI6MTY4MDc4MDU1NX0.cc7axJiz2shtrbDV6oy6Rie2wUck0eegtT7UF27gQ-A

{
  "customerId": 1,
  "products": [
    {
      "id": 1,
      "description": "아디다스 신발입니다.",
      "name": "아디다스 스탠스미스",
      "productItems": [
        {
          "count": 1,
          "id": 1,
          "name": "아디다스 스탠스미스 한정판",
          "price": 100000
        }
      ],
      "sellerId": 1
    }
  ],
  "messages": []
}